# Generated by Django 4.0.3 on 2022-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('cathedra', models.CharField(choices=[('1', 'Gryffindor'), ('2', 'Hufflepuff'), ('3', 'Ravenclaw'), ('4', 'Slytherin')], max_length=1)),
            ],
        ),
    ]
